server:
  port: 8097
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.132:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.130:3306/power_shop?characterEncoding=UTF-8
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: power-shop-order
  redis:
    cluster:
      nodes:
        - 192.168.174.134:7001
        - 192.168.174.134:7002
        - 192.168.174.134:7003
        - 192.168.174.134:7004
        - 192.168.174.134:7005
        - 192.168.174.134:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
#订单
ORDER_ID: ORDER_ID
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID: ORDER_ITEM_ID
SETNX_LOCK_ORDER_KEY: SETNX_LOCK_ORDER_KEY