server:
  port: 8096
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.132:8848
  application:
    name: power-shop-cart
  redis:
    cluster:
      nodes:
        - 192.168.174.134:7001
        - 192.168.174.134:7002
        - 192.168.174.134:7003
        - 192.168.174.134:7004
        - 192.168.174.134:7005
        - 192.168.174.134:7006
  rabbitmq:
    host: 192.168.174.137
    username: admin
    password: 1111
    virtual-host: /
    publisher-returns: true #开启消息退回回调
    publisher-confirm-type: correlated #开启消息确认回调
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
#购物车
CART_COOKIE_KEY: CART_COOKIE_KEY
CART_REDIS: CART_REDIS